"""Add US Overview Data model

Revision ID: 366b8395cd26
Revises: 590f77ff4f91
Create Date: 2025-05-13 11:55:50.656786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366b8395cd26'
down_revision: Union[str, None] = '590f77ff4f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('us_overview_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('real_gdp_growth', sa.Float(), nullable=True),
    sa.Column('real_gdp_level', sa.Float(), nullable=True),
    sa.Column('inflation_rate', sa.Float(), nullable=True),
    sa.Column('unemployment_rate', sa.Float(), nullable=True),
    sa.Column('treasury_10y_yield', sa.Float(), nullable=True),
    sa.Column('fed_funds_rate', sa.Float(), nullable=True),
    sa.Column('public_debt_gdp', sa.Float(), nullable=True),
    sa.Column('population_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_us_overview_data_date'), 'us_overview_data', ['date'], unique=False)
    op.drop_index('ix_test_table_id', table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.create_index('ix_test_table_id', 'test_table', ['id'], unique=False)
    op.drop_index(op.f('ix_us_overview_data_date'), table_name='us_overview_data')
    op.drop_table('us_overview_data')
    # ### end Alembic commands ###
